### ISSUE TITLE
Error inflating class com.marcinmoskala.arcseekbar.ArcSeekBar

### ISSUE THREAD

**Issue by MohamedFouad96** [MarcinMoskala/ArcSeekBar#2]
Error inflating class com.marcinmoskala.arcseekbar.ArcSeekBar

**Comment by MarcinMoskala** [comment]
Can you share Stack Trace from execution report?

**Comment by ArkadiuszKozlowski** [comment]
I have the same problem, nothing useful in stacktrace, just inflate exception:
`android.view.InflateException: Binary XML file line #81: Binary XML file line #81: Error inflating class com.marcinmoskala.arcseekbar.ArcSeekBar at [...]`

Layout design tab is more helpfull, when I add ArcSeekBar to layout it says:
`Failed to find the style corresponding to the id -1`

In [ArcSeekBar.kt](https://github.com/MarcinMoskala/ArcSeekBar/blob/master/lib/src/main/java/com/marcinmoskala/arcseekbar/ArcSeekBar.kt) you have:
`class ArcSeekBar @JvmOverloads constructor(
        context: Context,
        attrs: AttributeSet? = null,
        defStyle: Int = -1
) : View(context, attrs, defStyle) {`

Shouldn't defStyle be 0 by default?

**Comment by MarcinMoskala** [comment]
Indeed. Thanks a lot for this suggestion, and check out version 0.30 :)

**Comment by ArkadiuszKozlowski** [comment]
Still doesn't work for me in 0.30. Above problem is indeed gone, but I am still getting the `android.view.InflateException`. 
When i try to create this view programmatically I get:

`java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
                                                                     at com.marcinmoskala.arcseekbar.ArcSeekBar.<init>(ArcSeekBar.kt)
                                                                     at com.marcinmoskala.arcseekbar.ArcSeekBar.<init>(ArcSeekBar.kt:18)
                                                                     at com.marcinmoskala.arcseekbar.ArcSeekBar.<init>(ArcSeekBar.kt)`

It looks like this library works only with Kotlin projects (I have pure Java-Android project).

**Comment by MarcinMoskala** [comment]
@ArkadiuszKozlowski  can you check it for version 0.31? I checked in pure Java separate project and it is working. The problem was resolved when I back to the previous version of Gradle. I am not sure what was the reason, but kotlin-stdlib was not distributed as it should.

**Comment by ArkadiuszKozlowski** [comment]
@MarcinMoskala It's working now, thanks!
